= MuleSoft Certified Connector License Management
:keywords: connector, devkit, license, key, keygen, partner, paid

== Introduction

With *DevKit 3.8*, MuleSoft Certified Connector partners/developers, referred to here also as "partners", can manage their connector’s license natively with DevKit before the connector is packaged for release, ensuring only the partner's paid customers are using the connector.

Partners that have built a MuleSoft Certified Connector can give potential customers the chance to build a Mule application with their connector and test it on the Mule ESB bundled with Anypoint Studio. However, upon deploying the Mule application with the connector, customers are prompted for the partner's generated key ensuring they possess a valid license from the partner.

== Why Use This Licensing Mechanism

Using a MuleSoft-generated key ensures only the MuleSoft partner's paid customers have complete access to the paid version of the connector. Users who would like to test out the connector before purchasing it would be able to experiment with the connector in design in Anypoint Studio and run their application in Studio's embedded Mule runtime.

//todo: insert link to sample connector in this commented out sentence: Inspect this sample connector in Studio with Mule ESB to help you understand the user experience with the certified connector.
In trying to deploy this sample connector on CloudHub or Mule ESB On-Prem, you see a pop-up message requesting a valid license.

== To Obtain a Key and Keystore for Your Connector
//todo: please read these steps to ensure they are complete and are all the steps for the partner to do before submitting connector for certification
Before submitting the connector to MuleSoft for certification, the prospective certified connector partner should complete these steps:

. Include the following information for MuleSoft to use before generating a partner key and keystore.
.. *Vendor Name*, *Contact Email*, *Contact Message*, *Connector Name*
. Request the key from MuleSoft, which will be the public `.key` file that is bundled into the connector, and the `.jks` master keystore for the partner to generate licenses with.
.. The *provider* will be the part before the `.key` suffix of the file given by Mule. For example, if MuleSoft generated a vendor key using the name “prov-name.key”, then the provider name has to be “prov-name”.
. The partner then adjusts the connector project code accordingly by applying the `@RequiresEntitlement` annotation, and entering values for all requested attributes, `name`, which must be the name of the connector and the provider name, which must be set for the `provider` attribute.
+
[source, java, linenums]
----
@RequiresEntitlement(name="connector-name", provider="prov-name")
public class LicensedConnector {
  ...
----
.. Put the given `.key` file under the `src/main/resources` or `src/main/resources/license` folder in the connector’s project directory
. The partner uses the key and the keystore to produce a license file to send to the connector customer according to detailed instructions provided to you by MuleSoft.

== Developing a Mule Application with a Licensed Connector

For the customer to validate their working connector license, the customer must make their license (`.lic`) file available through either the Mule application or the Mule server.

=== License File in the Mule Application

Once the customer has already bought a license for the connector, the `.lic` file provided to the customer by the partner/vendor can be placed either:

* under `src/main/resources` in the application (developed in Studio) or,
* under `app/classes` if the application has already been unpacked and deployed on the server.

=== License File in the Mule Server

Instead of storing the license in the application, it can be placed instead in the `conf/` folder of the Mule server.

[NOTE]
This is the recommended approach if multiple applications require the same license.
