= Connector Testing Framework and Extensions
:keywords: connector testing framework, ctf, devkit, mule, esb, runtime

== Overview

The purpose of the connector testing framework (CTF) is to perform functional testing in as many deployment scenarios as possible. The framework runs a Mule app "externally", unbound to the versions of DevKit and Mule the connector was developed on.

//TODO: Insert matrix or link to Devkit/Mule compatibility

Using a simple Maven command, you can perform tests in the runtime specified in your local profile, in an embedded runtime or in multiple runtime versions on your CloudHub instance.
//TODO: support for "Remote Mule"

[NOTE]
The fact that libraries change on CloudHub increases the potential for *incompatibility* between the Mule runtime version and your DevKit-based connector.
//TODO: more info on this "library changing"

== Deployment Profile Configuration

Pass the desired connector application deployment details as arguments to a single Maven command, specifying the environments you want to test your connector in.
//environments, term correct?
If you do not specify `-Ddeploymentprofile`, otherwise the test will run by default in embedded mode.

=== Embedded Mode

Specifying only `mvn clean test` would run the functional tests in _embedded_ mode

//TODO:Briefly describe this embedded mode...this note doesn't make sense to me: Mule runtime where connector is executed is loaded into memory. It will load what is described in the CTF.

=== Local Mode

Local testing means loading Mule from your user profile. To test locally, run:

----
mvn clean test -Ddeploymentprofile= -Dmuledirectory=/local/usr/mule_3.6.3
----
//-Ddeploymentprofile argument needed? perhaps check if this references the argument via a file

=== CloudHub Mode

As of DevKit 3.8.0, CTF support for a CloudHub deployment profile is available, allowing you to test your connector in a more dynamic environment, a clear advantage to deploying a Mule application in a classic standalone environment. The two required parameters you must pass to the Maven command are your CloudHub username `-Dcloudhubuser=` and `-Dcloudhubpassword=`.

----
mvn clean test -Dcloudhubuser=<your_username> -Dcloudhubpassword=<your_password>
----

==== Optional Parameters

When testing on CloudHub, you may specify the Mule version to run connector tests on, the CloudHub URL and the CloudHub worker type for your instance. See the example below that includes both the required _and_ optional parameters:

----
mvn clean test -Dcloudhubuser=<your_username> -Dcloudhubpassword=<your_password>
-Dmuleversion=3.7.2
-DcloudhubURL=http://qa.anypointplatform.mulesoft.com/cloudhub
-Dcloudhubworkertype=small
----

////
== Remote Mule Mode

//TODO:
if feasible, how to run Mule App on Docker.

The main objective of CTF-Docker interaction is having the Docker daemon automatically start the Mule ESB servers, deploy the application and test the connector.
////
== Troubleshooting

////
Devkit plugin generates the scaffolding, which loads the tests for each of the methods.
//TODO: Where does CTF come into play?

what to do if your test failed
debug logging to show more info.
////

== Logging

When connector has a business logic exception
//TODO: Describe logs in Mule and how to access logs in CloudHub

== See Also
//TODO: CloudHub, Docker, Logs, CTF, Certification
