= Connector Testing Framework and Extensions
:keywords: connector testing framework, ctf, devkit, mule, esb, runtime

== Overview

The purpose of the connector testing framework (CTF) is to perform functional testing in as many deployment scenarios as possible. The framework runs a Mule app "externally", unbound to the versions of DevKit and Mule the connector was developed on.

Using a simple Maven command, you can perform tests in the runtime specified in your local profile, in an embedded runtime or in multiple runtime versions on your CloudHub instance.
//TODO: support for "Remote Mule"

[NOTE]
The fact that libraries change on CloudHub increases the potential for *incompatibility* between the Mule runtime version and your DevKit-based connector.
//TODO: more info on this "library changing"

== Deployment Profile Configuration

Pass the desired connector application deployment details as arguments to a single Maven command, specifying the environments you want to test your connector in. All arguments should be in lowercase.

If you do not specify `-Ddeploymentprofile`, otherwise the test will run by default in embedded mode.

=== Embedded Mode

Specifying only `mvn clean test` would run the functional tests in _embedded_ mode.

//TODO:Briefly describe this embedded mode...this note doesn't make sense to me: Mule runtime where connector is executed is loaded into memory. It will load what is described in the CTF.

=== Local Mode

Local testing means loading Mule from your user profile. To test locally `-Ddeploymentprofile` *must* be set in `/local`. For example, the command would be structured like:

----
mvn clean test -Ddeploymentprofile= -Dmuledirectory=/local/usr/mule_3.6.3
----


=== CloudHub Mode

As of DevKit 3.8.0, CTF support for a CloudHub deployment profile is available, allowing you to test your connector in a more dynamic environment, a clear advantage to deploying a Mule application in a classic standalone environment. The two required parameters you must pass to the Maven command are your CloudHub username `-Dcloudhubuser=` and `-Dcloudhubpassword=`.
//todo: check all commands with -Ddeploymentprofile=cloudhub
----
mvn clean test -Ddeploymentprofile=cloudhub -Dcloudhubuser=<your_username> -Dcloudhubpassword=<your_password>
----

==== Optional Parameters

When testing on CloudHub, you may specify the Mule version to run connector tests on, the CloudHub URL and the CloudHub worker type for your instance. See the example below that includes both the required _and_ optional parameters:


[cols=",,"options="header"]
|===
|Optional Parameters|Description
|`muleversion`| Configure the Mule runtime to be used on CloudHub
|`cloudhuburl`| Gives the capability of change the CloudHub instance, by default the CTF deploys to http://anypoint.mulesoft.com/cloudhub/
|`cloudhubworkertype` | Allows you to configure the desired amount of vCores for the Mule application to be generated. The available options are:
`micro` (0.1vCores),
`small` (0.2vCores), `medium` (1vCore), `large` (2vCores), `xlarge` (4vCores)
//todo: check each argument is printed above correctly
|`cloudhubtimeout`| Allows you to configure the timeout of the CloudHub instance where the Mule application is deployed
//todo:check above descrip for accuracy
|===

Example CTF testing command:
----
mvn clean test -Ddeploymentprofile=cloudhub -Dcloudhubuser=<your_username> -Dcloudhubpassword=<your_password>
-Dmuleversion=3.7.2
-DcloudhubURL=http://qa.anypointplatform.mulesoft.com/cloudhub
-Dcloudhubworkertype=small
----

////
== Remote Mule Mode

//TODO:
if feasible, how to run Mule App on Docker.

The main objective of CTF-Docker interaction is having the Docker daemon automatically start the Mule ESB servers, deploy the application and test the connector.
////
== Troubleshooting

////
what to do if your test failed
debug logging to show more info.
////

== Logging

//When connector has a business logic exception
//TODO: Describe logs in Mule and how to access logs in CloudHub

== See Also
For more information on CloudHub application management, see link:/cloudhub/managing-applications-and-servers-in-the-cloud-and-on-premises[Managing Applications and Servers in the Cloud and On Premises]
