= Connector License Management for Partners

== Introduction

With DevKit 3.8, MuleSoft partners can manage their connector’s license natively with DevKit, ensuring only paid customers are using the connector.

Partners that have built a MuleSoft Certified Connector can give potential customers the chance to build a Mule application with their connector and test it on the Mule ESB bundled with Anypoint Studio. However, upon deploying the Mule application with the connector, customers are prompted for the partner's generated key ensuring they possess a valid license from the partner.
//TODO: Use Nathan's description from tech spec. Is this pass called a key?

== Partner Perspective

=== Why Partner Should Use This Feature
//TODO: Why to choose this feature of key generation mechanism
//Video: show partner end user experience/flow if you implement
the key generation mechanism. Otherwise, you have to manage the keygen independently


=== Code Snippet Required @Annotation in Partner Java Class

=== Step 1 - what you need to do is provide additional information to get the key, before you release connector (for certified connectors only) in a form

=== How to generate the key

////
TODO: Separate documentation detailing User experience. At deployment, customer needs to provide the partner-provided Key to be able to use the connector in their application
////
