= Session Management for SOAP Connect
:keywords: soap connect, session management, wsdl, web service, soap

//TODO: how does session management improve the provisioning of the web service?
//TODO: what does this require the developer to code?
//TODO: Why is sessionID injection useful for the person administering a web service using a SOAP connector?

To enhance SOAP connector development, DevKit 3.8.0 comes equipped with session management options for SOAP Connect.

== Introduction

//TODO: The purpose of session management is...
Session management allows you, the developer to:

* Inject the sessionId into:
** HTTP cookies, and headers
** SOAP Headers
** SOAP Payload: chain of responsibility for managing the message payload. This might need to be managed by the WSDL Consumer.
//TODO: clarify above bullet point and what is implied by chain of responsibility
* Manage session expiration/timeout
* Acquire connection management intelligence (about configurations and reconnection)

== Requirements

//TODO: what does person reading this need to know besides the fact they need to implement these methods?

To enable session management for your connector, the `Config` class must be annotated with `@WsdlProvider` and `@ConnectionManagement`, which require implementation of the following methods:

For WSDL management:

* @WsdlServiceRetriever
* @WsdlServiceEndpoint

For Connection Management:

* @Connect
* @Disconnect
* @ValidateConnection

See the stub for the session management-enabled Config class in the <<@WsdlProvider with Session Management,@WsdlProvider with Session Management>> section.

== Connector Lifecycle with Session Management

The lifecycle of the connector will be modified by the "session control" mechanism during both fetching of metadata and invocation of operations. Before fetching metadata and invoking operations a connector instance will either be retrieved from the pool or be created, and the `@Connect` method invoked to initialize the connection.

//TODO: please expand on "session control" above

Connection pooling works in the same way as the current `@ConnectionManagement` mechanism, with the same kind of pool configuration available from a configuration tab, being responsible for handling existing connector instances or the creation of one y none exists in the pool.
//TODO: need clarification on above para. Which configuration tab? Need screenshot?

Since the `@Connect` method is invoked before any of the common `@WsdlProvider` methods, all the required parameters for connection must be provided via a `@Configurable` field or `@Connect` parameter. Initialization may take place inside the `@Connect` method in order to save results like session tokens. The WsdlResolver initialization will remain lazy up to the point where it is needed for metadata or processor invocations.

== @WsdlProvider with Session Management

See the structure of the `@WsdlProvider` Config class with session management implemented:
//TODO: describe session token's role in session management

[source,code,linenums]
----
@WsdlProvider(friendlyName = "Configuration")
@ConnectionManagement
public class Config {

    private String username;
    private String password;

    @Configurable
    @Default("http://localhost:8088/mockTshirt")
    @Placement(order = 3)
    private String endpoint;

    @Connect
    @TestConnectivity
    public void connect(@ConnectionKey String username, @Password String password)  throws ConnectionException {
        // obtain session token
    }

    @Disconnect
    public void disconnect() {
        // end connection
    }

    @ValidateConnection
    public boolean isConnected() {
        return false;
    }

    @WsdlServiceRetriever
    public ServiceDefinition getServiceDefinition() {
           return new DefaultServiceDefinition("ServiceID", "tshirt", "tshirt.wsdl","TshirtService","TshirtServicePort");
    }

    @WsdlServiceEndpoint
    public String getServiceEndpoint(ServiceDefinition definition) {
         return endpoint;
    }

    @WsdlHeaders
    public List<Document> cookHeaders(ServiceDefinition serviceDefinition, String operationName){
        // Customize headers with session token
    }

    @WsdlTransportRetriever
    public WsdlTransport resolveTransport(ServiceDefinition serviceDefinition) {
        return new HttpBasicWsdlTransport(getUsername(), getPassword());
    }

    // ...
}
----

== See Also
For more information on link:/anypoint-connector-devkit/v/3.7/creating-a-soap-connector[Creating a SOAP Connector]
