= SOAP Session Management
:keywords: soap connect, session management, wsdl, web service, soap

To support SOAP-based connector development, DevKit 3.8.0 comes equipped with the ability to define a session token for managing connections, SOAP sessions and service operations requiring a token.

== Introduction

Session management means the ability to create a session token in your connector code within the `@Connect` method, and utilize it as necessary for certain service operations.

Use the session ID as a means to manage user access to the service through the connector. For more information on session token placement inside the body see link:

Session management allows you, the developer to:

* Inject the session token into:
** HTTP cookies, and headers
//todo: do we need more information on HTTP cookies and headers?
** SOAP Headers
** SOAP Payload: chain of responsibility for managing the message payload. This might need to be managed by the WSDL Consumer.
* Manage session expiration/timeout
* Acquire connection management intelligence (about configurations and reconnection)
//todo: how to get connection management intelligence? is it that connections and sessions can be identified using the session token?

== Requirements

To enable session management for your connector, the `Config` class must be annotated with `@WsdlProvider` and `@ConnectionManagement`, which require implementation of the following methods, respectively:

For WSDL management:

* @WsdlServiceRetriever
* @WsdlServiceEndpoint

For Connection Management:

* @Connect
* @Disconnect
* @ValidateConnection

See the stub for the session management-enabled Config class in the <<@WsdlProvider with Session Management,@WsdlProvider with Session Management>> section.

== Connector Lifecycle with Session Management

The lifecycle of the connector will be modified by "session control", during both fetching of metadata and operation invocation. Before fetching metadata and invoking operations, a connector instance is retrieved from or created in the pool, and then the `@Connect` method would be invoked to initialize the connection.

Connection pooling works like the current `@ConnectionManagement` mechanism; by using the same kind of pool configuration available via a configuration tab. The use of existing connector instances or creation of new ones is handled.
//todo: are there two pools, one for connections, and one for connector objects? Is it unnecessary to include the above. It sounds like there is a separate pool for connections, and I'm not sure this is the case, or if the connection lives with the connector instance.

Since the `@Connect` method is invoked before any of the common `@WsdlProvider` methods, all the required parameters for connection must be provided via a `@Configurable` field or `@Connect` parameter. Initialization may take place inside the `@Connect` method in order to save results like session tokens. The `@WsdlResolver` initialization will remain lazy up to the point where it is needed for metadata or processor invocations.

== @WsdlProvider with Session Management

See the structure of the `@WsdlProvider` Config class below, noting that the session token should be created in the `@Connect` method for use in whichever part of the SOAP message is required, depending on the case:

[source,java,linenums]
----
@WsdlProvider(friendlyName = "Configuration")
@ConnectionManagement
public class Config {

    private String username;
    private String password;

    @Configurable
    @Default("http://localhost:8088/mockTshirt")
    @Placement(order = 3)
    private String endpoint;

    @Connect
    @TestConnectivity
    public void connect(@ConnectionKey String username,  @Password String password)  throws ConnectionException {
        // obtain session token
    }

    @Disconnect
    public void disconnect() {
        // end connection
    }

    @ValidateConnection
    public boolean isConnected() {
        return false;
    }

    @WsdlServiceRetriever
    public ServiceDefinition getServiceDefinition() {
           return new DefaultServiceDefinition("ServiceID", "tshirt", "tshirt.wsdl","TshirtService","TshirtServicePort");
    }

    @WsdlServiceEndpoint
    public String getServiceEndpoint(ServiceDefinition definition) {
         return endpoint;
    }

    @WsdlHeaders
    public List<Document> cookHeaders(ServiceDefinition serviceDefinition, String operationName){
        // Customize headers with session token
    }

    @WsdlTransportRetriever
    public WsdlTransport resolveTransport(ServiceDefinition serviceDefinition) {
        return new HttpBasicWsdlTransport(getUsername(), getPassword());
    }

    // ...
}
----

== See Also
For more information on link:/anypoint-connector-devkit/v/3.7/creating-a-soap-connector[Creating a SOAP Connector]
